### ISSUE TITLE
The stop.sh script loads modules which havent been unloaded during start.sh

### ISSUE THREAD

**Issue by sylvesterroos** [cosminmocan/vfio-single-amdgpu-passthrough#1]
Is this correct, or is it a mistake in the files?

**Comment by tamasfe** [comment]
I don't think they're important as long as you can unload `amdgpu` properly.

Depending on the system you might need to unload/reload multiple modules, e.g. any of these:

```bash
# lsmod | rg amdgpu
amdgpu               6737920  24
drm_ttm_helper         16384  1 amdgpu
ttm                    86016  2 amdgpu,drm_ttm_helper
iommu_v2               24576  1 amdgpu
gpu_sched              45056  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
drm_kms_helper        278528  1 amdgpu
drm                   561152  15 gpu_sched,drm_kms_helper,amdgpu,drm_ttm_helper,ttm
```

**Comment by cosminmocan** [comment]
> I don't think they're important as long as you can unload `amdgpu` properly.
> 
> Depending on the system you might need to unload/reload multiple modules, e.g. any of these:
> 
> ```shell
> # lsmod | rg amdgpu
> amdgpu               6737920  24
> drm_ttm_helper         16384  1 amdgpu
> ttm                    86016  2 amdgpu,drm_ttm_helper
> iommu_v2               24576  1 amdgpu
> gpu_sched              45056  1 amdgpu
> i2c_algo_bit           16384  1 amdgpu
> drm_kms_helper        278528  1 amdgpu
> drm                   561152  15 gpu_sched,drm_kms_helper,amdgpu,drm_ttm_helper,ttm
> ```

This !
